const words = [
   "REACT", "JAVASCRIPT", "GRID", "SEARCH", "COMPUTER", "ALGORITHM", "ARRAY", "FUNCTION",
    "VARIABLE", "OBJECT", "PROTOTYPE", "NODE", "MODULE", "REACTJS", "CSS", "HTML", "DATABASE",
    "SERVER", "CLIENT", "API", "ASYNC", "CALLBACK", "PROMISE", "LOOP", "CONDITIONAL", "STRING",
    "NUMBER", "BOOLEAN", "OBJECTS", "DEBUG", "CONSOLE"
];

export default words;
